apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: broadcast
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: broadcast
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /broadcast
    tls: ""
  method: ""
  methods:
  - GET
  relativeurl: /broadcast
