apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: web
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: web
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /chat/{html:[a-zA-Z0-9\.\/]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /chat/{html:[a-zA-Z0-9\.\/]+}
