include:
- getstock.py
kind: ArchiveUploadSpec
name: getstock-py-vdoD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getstock-768a1544-3c3a-441d-8028-1d3eb084103d
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://getstock-py-vdoD
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-02-10T03:47:19Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: getstock
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: getstock-768a1544-3c3a-441d-8028-1d3eb084103d
      namespace: default
  requestsPerPod: 1
  resources: {}
