apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: reorder
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: reorder
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /reorder
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /reorder
