include:
- hello-3-75.py
kind: ArchiveUploadSpec
name: hello-3-75-py-YJYT

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-3-75-3b057b77-e3a3-4694-80f2-8be7791f9012
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://hello-3-75-py-YJYT
  environment:
    name: python-3
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2020-09-24T12:31:02Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello-3-75
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 1800
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps: null
  environment:
    name: python-3
    namespace: default
  functionTimeout: 9000
  idletimeout: 900
  package:
    packageref:
      name: hello-3-75-3b057b77-e3a3-4694-80f2-8be7791f9012
      namespace: default
  resources: {}
  secrets: null
