include:
- hello-1-30.py
kind: ArchiveUploadSpec
name: hello-1-30-py-PhGa

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-6-30-db270786-b209-410b-983e-ae91f5342f4f
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://hello-1-30-py-PhGa
  environment:
    name: python-6
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2020-09-24T12:32:33Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello-6-30
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps: null
  environment:
    name: python-6
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: hello-6-30-db270786-b209-410b-983e-ae91f5342f4f
      namespace: default
  resources: {}
  secrets: null
