include:
- backend.zip
kind: ArchiveUploadSpec
name: backend-zip-d1Re

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: backend-pkg
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: pythonsrc
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://backend-zip-d1Re
status:
  buildstatus: pending
  lastUpdateTimestamp: "2021-12-30T02:48:03Z"
