apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: frontend
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: frontend
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /voteapp
    tls: ""
  method: ""
  methods:
  - POST
  - GET
  prefix: ""
  relativeurl: /voteapp
