
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: aws-credentials
stringData:                     # note that we are using string data, and not base64 encoded data
  awsAccessKeyID: access-key-id
  awsSecretAccessKey: secret-access-key
type: Opaque

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: queue-details
data:
  AWS_REGION: us-east-2
  QUEUE_URL: https://sqs.us-east-2.amazonaws.com/xxxxxxxxxxxx/input

