apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: monolith
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: monolith
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /monolith
    tls: ""
  method: ""
  methods:
  - POST
  - GET
  prefix: ""
  relativeurl: /monolith
