apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: nextapp
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: nextapp
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /nextapp/
    tls: ""
  method: ""
  methods:
  - GET
  prefix: /nextapp/
  relativeurl: ""
