include:
- consumer.js
kind: ArchiveUploadSpec
name: consumer-js-Sr7D

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: consumer-0dfea345-c8ee-4c68-8407-69d80ebddea6
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://consumer-js-Sr7D
  environment:
    name: nodeenv
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2022-01-25T06:07:18Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: consumer
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodeenv
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: consumer-0dfea345-c8ee-4c68-8407-69d80ebddea6
      namespace: default
  requestsPerPod: 1
  resources: {}
