include:
- pub/pub.py
- pub/requirements.txt
kind: ArchiveUploadSpec
name: pub-pub-py-rFZ4

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: producer-bc6909a7-13cd-4d60-bfb1-90a38c405ead
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python-gcp
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://pub-pub-py-rFZ4
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-01-25T06:05:54Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: producer
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python-gcp
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main
    packageref:
      name: producer-bc6909a7-13cd-4d60-bfb1-90a38c405ead
      namespace: default
  requestsPerPod: 1
  resources: {}
