apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: gcptest
  namespace: default
spec:
  contentType: application/json
  cooldownPeriod: 30
  errorTopic: error-topic
  functionref:
    functionweights: null
    name: consumer
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: gcp-pubsub
  metadata:
    credentialsFromEnv: GoogleApplicationCredentials
    subscriptionName: request-topic-sub
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 5
  respTopic: response-topic
  secret: pubsub-secret
  topic: request-topic-sub
