apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: kafka-producer
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: keda-kafka-configmap
    namespace: default
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: Handler
    packageref:
      name: kafka-producer
      namespace: default
  requestsPerPod: 1
  resources: {}
