apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: syschanges
  name: system-changes-sysds-node-exporter
spec:
  selector:
    matchLabels:
      component: "node-exporter"
      app: sysds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: "node-exporter"
        app: sysds
        heritage: Helm
    spec:
      containers:
        - name: busybox
          image: "busybox"
          command:
          - /bin/sh
          - -c
          - |
            sysctl -w net.ipv4.tcp_max_tw_buckets=65535
            #sysctl -w net.ipv4.tcp_tw_recycle=1
            sysctl -w net.ipv4.tcp_tw_reuse=0
            sysctl -w net.ipv4.tcp_max_syn_backlog=131072
            sysctl -w net.ipv4.tcp_syn_retries=3
            sysctl -w net.ipv4.tcp_synack_retries=3
            sysctl -w net.ipv4.tcp_retries1=3
            sysctl -w net.ipv4.tcp_retries2=8
            sysctl -w net.ipv4.tcp_rmem="16384 174760 349520"
            sysctl -w net.ipv4.tcp_wmem="16384 131072 262144"
            sysctl -w net.ipv4.tcp_mem="262144 524288 1048576"
            sysctl -w net.ipv4.tcp_max_orphans=65536
            sysctl -w net.ipv4.tcp_fin_timeout=10
            sysctl -w net.ipv4.tcp_low_latency=1
            sysctl -w net.ipv4.tcp_syncookies=0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            privileged: true
          resources:
            {}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys