{
 "title": "Fission Functions",
 "description": "Fission serverless dashboards.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Functions Calls Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fission_function_calls_total) by (name)",
     "legendFormat": "{{name}}  ({{method}} {{path}})"
    }
   ]
  },
  {
   "title": "Functions Alive",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fission_func_is_alive", "legendFormat": "{{funcname}}" }
   ]
  },
  {
   "title": "Functions Cold Start Total",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fission_cold_starts_total", "legendFormat": "{{funcname}} - {{funcuid}}" }
   ]
  },
  {
   "title": "Functions 500 Response",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(delta(fission_function_calls_total{code=\"500\"}[2m])) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Functions Duration @ Quantile 0.9",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "fission_function_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}