import Head from 'next/head'
import Image from 'next/image'

import blogs from '../data/blogs.json'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://fission.io">Fission!</a>
        </h1>

        <p className={styles.description}>
          Kubernetes-native Serverless Framework          
        </p>

        <div className={styles.grid}>          
          {blogs.map(blog => (
            <a href={`/${blog.slug}`} className={styles.card}>
              <h2>{blog.title} &rarr;</h2>
              <p>{blog.author}</p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>        
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={20} />
        </span>
        <span className={styles.logo}>
          <Image src="/fission.png" alt="Fission Logo" width={72} height={20} />
        </span>        
      </footer>
    </div>
  )
}
