include:
- function1.zip
kind: ArchiveUploadSpec
name: function1-zip-kXR3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: function1-pkg
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: my-env
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://function1-zip-kXR3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-02-25T14:03:08Z"
