apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: next-blog
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: nextjs-func
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /nextapp
    tls: ""
  keepPrefix: true
  method: ""
  methods:
  - GET
  - POST
  prefix: /nextapp
  relativeurl: ""
