include:
- falco-pod-delete/*
kind: ArchiveUploadSpec
name: falco-pod-delete-sBo7

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: falco-pod-delete-d18f6a0b-e5a1-4275-9471-38d684ac4dfe
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://falco-pod-delete-sBo7
status:
  buildstatus: pending
  lastUpdateTimestamp: "2021-07-19T10:16:44Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: falco-pod-delete
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: go
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: Handler
    packageref:
      name: falco-pod-delete-d18f6a0b-e5a1-4275-9471-38d684ac4dfe
      namespace: default
  requestsPerPod: 1
  resources: {}
