apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: falco-pod-delete
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: falco-pod-delete
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /falco-pod-delete
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /falco-pod-delete
