include:
- entry.sh
- goprog
kind: ArchiveUploadSpec
name: entry-sh-clRt

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: bfunc-86c06233-f5e8-40b4-8b2c-3a2065ee5d79
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://entry-sh-clRt
  environment:
    name: binary
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2020-09-18T15:53:08Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: bfunc
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 5
  configmaps: null
  environment:
    name: binary
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: entry.sh
    packageref:
      name: bfunc-86c06233-f5e8-40b4-8b2c-3a2065ee5d79
      namespace: default
  resources: {}
  secrets: null
